export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const OBTENER_POSTS = 'OBTENER_POSTS';
export const OBTENER_POST = 'OBTENER_POST';
export const AGREGAR_POST = 'AGREGAR_POST';
export const POST_EXITOSO = 'POST_EXITOSO';
export const POST_ERROR = 'POST_ERROR';
export const POST_ACTUAL = 'POST_ACTUAL';
export const ELIMINAR_POST = 'ELIMINAR_POST';
export const ACTUALIZAR_POST = 'ACTUALIZAR_POST';